### ISSUE TITLE
Using pretrained with inference

### ISSUE THREAD

**Issue by Entretoize** [shangwei5/VIDUE#4]
You lin to pretrained data needs special software installation that we can't install in france, don't you have a direct link ?

Thanks

**Comment by shangwei5** [comment]
We have provided the download link for Google Drive : https://drive.google.com/drive/folders/1iiQGGzsczKG8eqORqT_qq_F04CEQTQUu?usp=sharing

**Comment by Entretoize** [comment]
Yes sorry I read to fast, thanks !

**Comment by Entretoize** [comment]
I can't get your inference working with my data, I checked the structure you propose but it doesn't work.
I understood that frame names should be number, ok, but does a substraction (`int(filename)-(self.m//2)+j)`) whi gives an error (`FileNotFoundError: No such file: 'D:\git\VIDUE\dataset\train\video1\-00001.png'`)
So I removed `-(self.m//2)+j)` but now the size seems incompatible : `ValueError: operands could not be broadcast together with shapes (752,752,3) (1512,1512,3)`
Can you help ?

**Comment by Entretoize** [comment]
I got something by duplicating my frame into ground truth folder and doubling the images dimensions (still with `-(self.m//2)+j` removed), but I suppose that's not the good way.
Why do I need ground truth dataset for inferencing ?? Why the dimension should be doubled ? What is the right way ?

**Comment by shangwei5** [comment]
If you test on your own real-world data, please use `python inference_vidue_worsu_real.py` as we mentioned in readme.
Changing `--m`, `--n`, and `--n_outputs` according to yours. 
If the effect is still not good, you can follow the training instructions in our Readme to finetune the model on your dataset.

**Comment by Entretoize** [comment]
Sorry I rad this line in the readme several time but didn't even see the script was not the same. 
Thanks you for replying. I will try a finetune too.
