### ISSUE TITLE
关于推理的问题

### ISSUE THREAD

**Issue by xy1565838851** [shangwei5/VIDUE#5]
没有泛化性，在通用数据集上表现难以接受，是一篇纯学术研究

**Comment by shangwei5** [comment]
我们在paper做了泛化实验，在相同训练策略下我们的方法优于现有方法，如果你想直接用于别的数据集可以自己finetune

**Comment by xy1565838851** [comment]
嗯嗯，您的回复也是在证实同样的事情：对于不同的数据集要进行相应的finetune，所以感觉是非常好的学术成果，但是和实际工程应用存在距离
